title: Nazario Software
email: nazariosoftwarellc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hand-raised, free-range apps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nazariosoftware.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: NazarioSoftware
github_username:  nazariosoftwarellc

# Build settings
remote_theme: jeffreytse/jekyll-theme-yat
plugins:
  - jekyll-remote-theme
  - jekyll-feed
