title: Nazario Software
email: nazariosoftwarellc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hand-raised, free-range browser extensions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nazariosoftware.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kbn_au
github_username:  nazariosoftwarellc
google_analytics: G-9VDRKH28JY
author: Nazario Software LLC
copyright: 2020

# Build settings
remote_theme: nazariosoftwarellc/jekyll-theme-yat
plugins:
  - jekyll-remote-theme
  - jekyll-feed
